dist: xenial
language: python
python:
- '3.7'
addons:
  apt:
    packages:
    - ffmpeg
install:
- pip install pipenv
- make install-test
script:
- make test

# Deploy to Sapir:
after_success:
- openssl aes-256-cbc -K $encrypted_cf988b8ff923_key -iv $encrypted_cf988b8ff923_iv -in recval.key.enc -out recval.key -d
deploy:
  provider: script
  skip_cleanup: true
  script: curl --verbose --fail --data-urlencode secret@recval.key sapir.artsrn.ualberta.ca/redeploy/recval
