sudo: false
language: python
python:
 - '3.7-dev'
addons:
  apt:
    sources:
      - trusty-media
    packages:
     - ffmpeg
install:
 - pip install pipenv
 - make install-test
script:
 - make test
