sudo: false
language: python
python:
 - '3.7-dev'
install:
 - pip install pipenv
 - make install-test
addons:
  apt:
    sources:
      - trusty-media
    packages:
     - ffmpeg
script:
 - make test
