sudo: false
language: python
python:
 - '3.7-dev'
install:
 - pip install pipenv
 - pipenv install --dev
 - pipenv run python init.py
addons:
  apt:
    packages:
     - ffmpeg
script:
 - pipenv run py.test
