#!/bin/bash

set -eux

# Change into directory containing THIS SCRIPT
# (and presumably the docker-compose.yml file)
cd "$(dirname "$0")"

git pull
docker-compose down
docker rmi -f speechdb_web
docker build --compress -t speechdb_web .
docker-compose up -d --remove-orphans
