#!/bin/bash

set -eux

# Change into directory containing THIS SCRIPT
# (and presumably the docker-compose.yml file)
cd "$(dirname "$0")"

git pull
docker build .
docker-compose up -d --remove-orphans
