version: '3'
services:
    web:
        build: .
        restart: always
        ports:
        - "8004:8000"
        volumes:
        # HOST : CONTAINER
        - "./.env:/app/.env"
        - "./db.sqlite3:/app/db.sqlite3"
        - "/data/application-data/speech-db/audio:/app/data/audio"
        - "/data/application-data/speech-db/speakers:/app/validation/static/images/speakers"
        - "/data/maskwacis-recordings/sessions:/app/data/sessions"
        - "/data/maskwacis-recordings/speakers:/app/data/speakers"
        - "/data/maskwacis-recordings:/data/maskwacis-recordings"
        - "/data/application-data/speech-db/metadata.csv:/app/private/metadata.csv"
        - "/data/application-data/speech-db/tsuutina-metadata.csv:/app/private/tsuutina-metadata.csv"
        - "/data/application-data/speech-db/tsuutina-recordings:/app/data/tsuutina"
        - "/data/application-data/speech-db/tsuutina-annotations:/app/data/tsuutina-annotations"
        - "/data/application-data/speech-db/tvpd-sessions:/app/data/tvpd-sessions"
        - "/data/application-data/speech-db/pfn-audio:/app/data/pfn-audio"
        - "/data/application-data/speech-db/wapamewwav:/app/data/wapamewwav"
