version: '3'
services:
    web:
        build: .
        restart: always
        ports:
        - "8004:8000"
        volumes:
        # HOST : CONTAINER
        - "./.env:/app/.env"
        - "./db.sqlite3:/app/db.sqlite3"
        - "/data/application-data/speech-db/audio:/app/data/audio"
