version: '3'
services:
    web:
        build: .
        restart: always
        ports:
        - "8004:8000"
        tmpfs:
        - "/opt/speech-db"
        volumes:
        # HOST : CONTAINER
        - "./.env:/app/.env"
        - "./db.sqlite3:/app/db.sqlite3"
        - "/data/application-data/speech-db/audio:/app/data/audio"
        - "/data/application-data/speech-db/speakers:/app/validation/static/images/speakers"
        - "/data/maskwacis-recordings/sessions:/app/data/sessions"
        - "/data/maskwacis-recordings/speakers:/app/data/speakers"
        - "/data/application-data/speech-db/metadata.csv:/app/private/metadata.csv"
        - "/data/application-data/speech-db/synth-speech:/app/data/synth-speech"
