version: '3'
services:
    web:
        build: .
        image: speechdb_web
        restart: always
        ports:
        - "8004:8000"
        volumes:
        # HOST : CONTAINER
        - "./.env:/app/.env"
        - "./db.sqlite3:/app/db.sqlite3"
        - "./crk.zhfst:/app/crk.zhfst"
        - "/data/application-data/speech-db/audio:/app/data/audio"
        - "/data/application-data/speech-db/speakers:/app/validation/static/images/speakers"
        - "/data/maskwacis-recordings/sessions:/app/data/sessions"
        - "/data/maskwacis-recordings/speakers:/app/data/speakers"
        - "/data/application-data/speech-db/metadata.csv:/app/private/metadata.csv"
        - "/data/application-data/speech-db/elicitation-sheets:/app/private/elicitation-sheets"
        - "/data/application-data/speech-db/synth-speech:/app/data/synth-speech"
        - "/data/application-data/speech-db/okimasis-recordings:/app/data/okimasis-recordings"
        - "/data/application-data/speech-db/i3-audio:/app/data/i3-audio"
        - "/data/application-data/speech-db/okimasis-bios:/app/data/okimasis-bios"
