version: '3.7'
services:
    web:
        build: .
        ports:
            - 127.0.0.1:8000:8000
        volumes:
            - "./db.sqlite3:/app/db.sqlite3"
            - "./data/audio:/app/data/audio"
