#!/bin/sh

# Does a type-check, and runs py.test.
# Any additional arguments are passed to py.test
#
# Useful arguments:
#  -s       -- show stdout and stderr
#  --pdb    -- launch pdb on test failures

mypy recval && py.test -Wd --driver Firefox "$@"
