# Generated by Django 2.2.19 on 2021-02-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="transcription",
            field=models.CharField(
                help_text="The validated transciption of the Cree phrase.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="transcription",
            field=models.CharField(
                help_text="The validated transciption of the Cree phrase.",
                max_length=256,
            ),
        ),
    ]
