# Generated by Django 2.2.19 on 2021-03-19 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="field_transcription",
            field=models.CharField(
                help_text="The transcription from the day of the recording. This should never change.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="field_transcription",
            field=models.CharField(
                help_text="The transcription from the day of the recording. This should never change.",
                max_length=256,
            ),
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="The comment left by the validator",
                        max_length=1024,
                    ),
                ),
                (
                    "other_reason",
                    models.CharField(
                        blank=True,
                        help_text="A reason other than the options provided for why the issue was filed",
                        max_length=1024,
                    ),
                ),
                (
                    "other",
                    models.BooleanField(
                        default=False,
                        help_text="There's another reason this issue was filed",
                    ),
                ),
                (
                    "bad_cree",
                    models.BooleanField(
                        default=False,
                        help_text="There's a better Cree word for this translation",
                    ),
                ),
                (
                    "bad_english",
                    models.BooleanField(
                        default=False,
                        help_text="There's another English word for this transcription",
                    ),
                ),
                (
                    "bad_recording",
                    models.BooleanField(
                        default=False,
                        help_text="There's one or more bad recordings in this batch",
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="validation.Phrase",
                    ),
                ),
            ],
        ),
    ]
