# Generated by Django 2.2.15 on 2020-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0001_squashed_0025_auto_20181221_1129"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="compressed_audio",
            field=models.FileField(blank=True, upload_to="audio/"),
        ),
    ]
