# Generated by Django 2.2.19 on 2021-03-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="field_transcription",
            field=models.CharField(
                help_text="The transcription from the day of the recording. This should never change.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="field_transcription",
            field=models.CharField(
                help_text="The transcription from the day of the recording. This should never change.",
                max_length=256,
            ),
        ),
    ]
