# Generated by Django 2.1.2 on 2018-10-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("validation", "0002_recordingsession_date")]

    operations = [
        migrations.AlterField(
            model_name="recordingsession",
            name="date",
            field=models.DateTimeField(help_text="The day the session occured"),
        )
    ]
