# Generated by Django 2.2.15 on 2020-08-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0002_recording_compressed_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="compressed_audio",
            field=models.FileField(upload_to="audio/"),
        ),
    ]
