# Generated by Django 2.2.18 on 2021-02-10 23:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [
        ("validation", "0003_auto_20200805_1549"),
        ("validation", "0004_auto_20210107_1323"),
        ("validation", "0005_auto_20210107_1342"),
        ("validation", "0006_auto_20210121_1035"),
        ("validation", "0007_auto_20210121_1039"),
        ("validation", "0008_auto_20210121_1042"),
        ("validation", "0009_auto_20210121_1042"),
        ("validation", "0010_auto_20210125_1340"),
        ("validation", "0011_auto_20210126_0924"),
        ("validation", "0012_auto_20210126_1109"),
        ("validation", "0013_auto_20210126_1141"),
    ]

    dependencies = [
        ("validation", "0002_recording_compressed_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="compressed_audio",
            field=models.FileField(upload_to="audio/"),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="analysis",
            field=models.CharField(
                blank=True, help_text="The analysis of the Cree phrase", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2021, 1, 26, 18, 41, 47, 595700, tzinfo=utc),
                editable=False,
                help_text="When was this phrase last modified?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="modifier",
            field=models.CharField(
                default="AUTO",
                help_text="The person who added or modified the phrase",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="analysis",
            field=models.CharField(
                blank=True, help_text="The analysis of the Cree phrase", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(2021, 1, 26, 18, 41, 53, 456413, tzinfo=utc),
                help_text="When was this phrase last modified?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phrase",
            name="modifier",
            field=models.CharField(
                default="AUTO",
                help_text="The person who added or modified the phrase",
                max_length=64,
            ),
        ),
    ]
