# Generated by Django 2.2.19 on 2021-03-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0002_auto_20210323_1627"),
        ("validation", "0002_auto_20210319_1640"),
    ]

    operations = []
