# Generated by Django 2.2.18 on 2021-02-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0003_auto_20200805_1549_squashed_0013_auto_20210126_1141"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecording",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="The comment provided in the ELAN file",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="The comment provided in the ELAN file",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad"), ("unknown", "Unknown")],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad"), ("unknown", "Unknown")],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=7,
            ),
        ),
    ]
