# Generated by Django 2.2.17 on 2021-01-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0003_auto_20200805_1549"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="speaker",
            field=models.CharField(
                default=False,
                help_text="Short code assigned to speaker in the ellicitation metadata.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="speaker",
            field=models.CharField(
                default=False,
                help_text="Short code assigned to speaker in the ellicitation metadata.",
                max_length=8,
            ),
        ),
    ]
