# Generated by Django 2.2.20 on 2021-05-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("validation", "0004_auto_20210326_1039"),
        ("validation", "0005_auto_20210407_1026"),
        ("validation", "0006_auto_20210414_1452"),
        ("validation", "0007_auto_20210423_1505"),
        ("validation", "0008_auto_20210423_1629"),
        ("validation", "0009_auto_20210428_0933"),
        ("validation", "0010_auto_20210428_1014"),
        ("validation", "0011_auto_20210428_1100"),
        ("validation", "0012_auto_20210428_1148"),
        ("validation", "0013_auto_20210428_1551"),
        ("validation", "0014_auto_20210429_1616"),
        ("validation", "0015_auto_20210430_0942"),
    ]

    dependencies = [
        ("validation", "0003_merge_20210326_1021"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="created_by",
            field=models.CharField(
                default="", help_text="The person who filed this issue", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="comment",
            field=models.CharField(
                help_text="The comment left by the validator", max_length=1024
            ),
        ),
        migrations.RemoveField(
            model_name="issue",
            name="other_reason",
        ),
        migrations.AddField(
            model_name="issue",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="validation.Recording",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="phrase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="validation.Phrase",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="The comment left by the validator",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("good", "Good"),
                    ("bad", "Bad"),
                    ("unknown", "Unknown"),
                    ("wrong speaker", "Wrong Speaker"),
                    ("wrong word", "Wrong Word"),
                ],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("good", "Good"),
                    ("bad", "Bad"),
                    ("unknown", "Unknown"),
                    ("wrong speaker", "Wrong Speaker"),
                    ("wrong word", "Wrong Word"),
                ],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="historicalphrase",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("auto-standardized", "Auto-standardized"),
                    ("standardized", "Standardized"),
                    ("linked", "Linked"),
                    ("validated", "Validated"),
                    ("needs review", "Needs review"),
                ],
                default="new",
                help_text="Status in the validation process",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("auto-standardized", "Auto-standardized"),
                    ("standardized", "Standardized"),
                    ("linked", "Linked"),
                    ("validated", "Validated"),
                    ("needs review", "Needs review"),
                ],
                default="new",
                help_text="Status in the validation process",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad"), ("unknown", "Unknown")],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad"), ("unknown", "Unknown")],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="The comment left by the validator",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="comment",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The comment left by the validator",
                max_length=1024,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issue",
            name="created_on",
            field=models.DateField(help_text="When was this issue filed?"),
        ),
        migrations.AddField(
            model_name="issue",
            name="suggested_cree",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Cree spelling suggested by the validator",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="suggested_english",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The English spelling suggested by the validator",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="historicalrecording",
            name="wrong_speaker",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong speaker"
            ),
        ),
        migrations.AddField(
            model_name="historicalrecording",
            name="wrong_word",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong word"
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="wrong_speaker",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong speaker"
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="wrong_word",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong word"
            ),
        ),
    ]
