# Generated by Django 2.2.19 on 2021-03-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0004_auto_20210326_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="created_on",
            field=models.DateField(help_text="When was this issue filed?"),
        ),
    ]
