# Generated by Django 2.2.17 on 2021-01-21 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0005_auto_20210107_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phrase",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date",
            ),
            preserve_default=False,
        ),
    ]
