# Generated by Django 2.2.19 on 2021-04-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0005_auto_20210407_1026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="The comment left by the validator",
                max_length=1024,
            ),
        ),
    ]
