# Generated by Django 2.2.20 on 2021-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0006_auto_20210414_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecording",
            name="wrong_speaker",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong speaker"
            ),
        ),
        migrations.AddField(
            model_name="historicalrecording",
            name="wrong_word",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong word"
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="wrong_speaker",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong speaker"
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="wrong_word",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong word"
            ),
        ),
        migrations.AlterField(
            model_name="historicalphrase",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("auto-standardized", "Auto-standardized"),
                    ("standardized", "Standardized"),
                    ("linked", "Linked"),
                    ("validated", "Validated"),
                    ("needs review", "Needs review"),
                ],
                default="new",
                help_text="Status in the validation process",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad"), ("unknown", "Unknown")],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("auto-standardized", "Auto-standardized"),
                    ("standardized", "Standardized"),
                    ("linked", "Linked"),
                    ("validated", "Validated"),
                    ("needs review", "Needs review"),
                ],
                default="new",
                help_text="Status in the validation process",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad"), ("unknown", "Unknown")],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
    ]
