# Generated by Django 2.1.2 on 2018-10-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0006_auto_20181018_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingsession',
            name='location',
            field=models.CharField(choices=[('DOWNSTAIRS', 'DS'), ('UPSTAIRS', 'US'), ('KITCHEN', 'KCH'), ('OFFICE', 'OFF')], default=None, help_text='The location of the recordings. May be null.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recordingsession',
            name='subsession',
            field=models.IntegerField(default=None, help_text="The 'subsession' number, if applicable.", null=True),
        ),
        migrations.AlterField(
            model_name='recordingsession',
            name='time_of_day',
            field=models.CharField(choices=[('MORNING', 'AM'), ('AFTERNOON', 'PM')], default=None, help_text='The time of day the session occured. May be null.', max_length=9, null=True),
        ),
    ]
