# Generated by Django 2.2.17 on 2021-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0006_auto_20210121_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="analysis",
            field=models.CharField(
                blank=True, help_text="The analysis of the Cree phrase", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="modifier",
            field=models.CharField(
                default="AUTO",
                help_text="The person who added or modified the phrase",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="analysis",
            field=models.CharField(
                blank=True, help_text="The analysis of the Cree phrase", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="modifier",
            field=models.CharField(
                default="AUTO",
                help_text="The person who added or modified the phrase",
                max_length=64,
            ),
        ),
    ]
