# Generated by Django 2.2.20 on 2021-04-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0006_auto_20210414_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrecording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("good", "Good"),
                    ("bad", "Bad"),
                    ("unknown", "Unknown"),
                    ("wrong speaker", "Wrong Speaker"),
                    ("wrong word", "Wrong Word"),
                ],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("good", "Good"),
                    ("bad", "Bad"),
                    ("unknown", "Unknown"),
                    ("wrong speaker", "Wrong Speaker"),
                    ("wrong word", "Wrong Word"),
                ],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
    ]
