# Generated by Django 2.2.20 on 2021-04-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0007_auto_20210423_1505"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("auto-standardized", "Auto-standardized"),
                    ("standardized", "Standardized"),
                    ("linked", "Linked"),
                    ("validated", "Validated"),
                    ("needs review", "Needs review"),
                ],
                default="new",
                help_text="Status in the validation process",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("auto-standardized", "Auto-standardized"),
                    ("standardized", "Standardized"),
                    ("linked", "Linked"),
                    ("validated", "Validated"),
                    ("needs review", "Needs review"),
                ],
                default="new",
                help_text="Status in the validation process",
                max_length=17,
            ),
        ),
    ]
