# Generated by Django 2.2.20 on 2021-05-13 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("validation", "0007_wrong_word_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wordform",
                    models.CharField(help_text="The entry headword", max_length=256),
                ),
                (
                    "analysis",
                    models.CharField(help_text="The FST analysis", max_length=256),
                ),
                (
                    "lemma",
                    models.CharField(
                        blank=True,
                        help_text="Is typically the 3S+Ind form of a verb",
                        max_length=64,
                    ),
                ),
                (
                    "stem",
                    models.CharField(blank=True, help_text="FST stem", max_length=64),
                ),
                (
                    "inflectional_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INM", "INM"),
                            ("IPC", "IPC"),
                            ("IPJ", "IPJ"),
                            ("NA1", "NA-1"),
                            ("NA2", "NA-2"),
                            ("NA3", "NA-3"),
                            ("NA4", "NA-4"),
                            ("NA4w", "NA-4w"),
                            ("NDA1", "NDA-1"),
                            ("NDA2", "NDA-2"),
                            ("NDA3", "NDA-3"),
                            ("NDA4", "NDA-4"),
                            ("NDA4w", "NDA-4w"),
                            ("NDI1", "NDI-1"),
                            ("NDI2", "NDI-2"),
                            ("NDI3", "NDI-3"),
                            ("NDI4", "NDI-4"),
                            ("NDI5", "NDI-5"),
                            ("PrA", "PrA"),
                            ("VAI", "VAI"),
                            ("VAI1", "VAI-1"),
                            ("VAI2", "VAI-2"),
                            ("VAI3", "VAI-3"),
                            ("VII1n", "VII-1n"),
                            ("VII1v", "VII-1v"),
                            ("VII2n", "VII-2n"),
                            ("VII2v", "VII-2v"),
                            ("VIIn", "VII-n"),
                            ("VIIv", "VII-v"),
                            ("VTA1", "VTA-1"),
                            ("VTA2", "VTA-2"),
                            ("VTA3", "VTA-3"),
                            ("VTA4", "VTA-4"),
                            ("VTA5", "VTA-5"),
                            ("VTI1", "VTI-1"),
                            ("VTI2", "VTI-2"),
                            ("VTI3", "VTI-3"),
                        ],
                        max_length=8,
                    ),
                ),
                ("derivational_analysis", models.CharField(blank=True, max_length=64)),
                (
                    "translation",
                    models.CharField(
                        help_text="The literal translation of the word", max_length=64
                    ),
                ),
                (
                    "edited_by",
                    models.CharField(
                        help_text="The last person to edit this word", max_length=64
                    ),
                ),
                (
                    "edited_on",
                    models.DateField(help_text="The date of the most recent change"),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="validation.Phrase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalWord",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "wordform",
                    models.CharField(help_text="The entry headword", max_length=256),
                ),
                (
                    "analysis",
                    models.CharField(help_text="The FST analysis", max_length=256),
                ),
                (
                    "lemma",
                    models.CharField(
                        blank=True,
                        help_text="Is typically the 3S+Ind form of a verb",
                        max_length=64,
                    ),
                ),
                (
                    "stem",
                    models.CharField(blank=True, help_text="FST stem", max_length=64),
                ),
                (
                    "inflectional_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INM", "INM"),
                            ("IPC", "IPC"),
                            ("IPJ", "IPJ"),
                            ("NA1", "NA-1"),
                            ("NA2", "NA-2"),
                            ("NA3", "NA-3"),
                            ("NA4", "NA-4"),
                            ("NA4w", "NA-4w"),
                            ("NDA1", "NDA-1"),
                            ("NDA2", "NDA-2"),
                            ("NDA3", "NDA-3"),
                            ("NDA4", "NDA-4"),
                            ("NDA4w", "NDA-4w"),
                            ("NDI1", "NDI-1"),
                            ("NDI2", "NDI-2"),
                            ("NDI3", "NDI-3"),
                            ("NDI4", "NDI-4"),
                            ("NDI5", "NDI-5"),
                            ("PrA", "PrA"),
                            ("VAI", "VAI"),
                            ("VAI1", "VAI-1"),
                            ("VAI2", "VAI-2"),
                            ("VAI3", "VAI-3"),
                            ("VII1n", "VII-1n"),
                            ("VII1v", "VII-1v"),
                            ("VII2n", "VII-2n"),
                            ("VII2v", "VII-2v"),
                            ("VIIn", "VII-n"),
                            ("VIIv", "VII-v"),
                            ("VTA1", "VTA-1"),
                            ("VTA2", "VTA-2"),
                            ("VTA3", "VTA-3"),
                            ("VTA4", "VTA-4"),
                            ("VTA5", "VTA-5"),
                            ("VTI1", "VTI-1"),
                            ("VTI2", "VTI-2"),
                            ("VTI3", "VTI-3"),
                        ],
                        max_length=8,
                    ),
                ),
                ("derivational_analysis", models.CharField(blank=True, max_length=64)),
                (
                    "translation",
                    models.CharField(
                        help_text="The literal translation of the word", max_length=64
                    ),
                ),
                (
                    "edited_by",
                    models.CharField(
                        help_text="The last person to edit this word", max_length=64
                    ),
                ),
                (
                    "edited_on",
                    models.DateField(help_text="The date of the most recent change"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="validation.Phrase",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical word",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
