# Generated by Django 2.2.20 on 2021-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0007_wrong_word_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("resolved", "Resolved"), ("open", "Open")],
                default="open",
                help_text="The status of the issue",
                max_length=64,
            ),
        ),
    ]
