# Generated by Django 2.2.17 on 2021-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0007_auto_20210121_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="analysis",
            field=models.CharField(
                default="None",
                help_text="The analysis of the Cree phrase",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="analysis",
            field=models.CharField(
                default="None",
                help_text="The analysis of the Cree phrase",
                max_length=256,
            ),
        ),
    ]
