# Generated by Django 2.2.24 on 2021-07-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0008_remove_booleans_from_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="crk_bio_audio",
            field=models.FileField(blank=True, upload_to="audio/"),
        ),
        migrations.AddField(
            model_name="speaker",
            name="crk_bio_text",
            field=models.CharField(
                blank=True,
                help_text="The Cree transcription of the speaker bio",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="speaker",
            name="eng_bio_audio",
            field=models.FileField(blank=True, upload_to="audio/"),
        ),
        migrations.AddField(
            model_name="speaker",
            name="eng_bio_text",
            field=models.CharField(
                blank=True,
                help_text="The English transcription of the speaker bio",
                max_length=2048,
                null=True,
            ),
        ),
    ]
