# Generated by Django 2.2.20 on 2021-04-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0008_auto_20210423_1629"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wrong_word",
                    models.BooleanField(
                        default=False,
                        help_text="This recording features the wrong word",
                    ),
                ),
                (
                    "wrong_speaker",
                    models.BooleanField(
                        default=False,
                        help_text="This recording features the wrong speaker",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historicalrecording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad"), ("unknown", "Unknown")],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad"), ("unknown", "Unknown")],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="historicalrecording",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="validation.Status",
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="validation.Status",
            ),
        ),
    ]
