# Generated by Django 2.2.20 on 2021-04-28 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0009_auto_20210428_0933"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="modified_by",
            field=models.CharField(
                default="",
                help_text="The person/people who modified this issue",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="modified_on",
            field=models.DateField(
                default=datetime.datetime(2021, 4, 28, 10, 14, 4, 406897),
                help_text="The date this issue was last updated",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="status",
            name="wrong_speaker",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong speaker"
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="wrong_word",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong word"
            ),
        ),
    ]
