# Generated by Django 2.2.17 on 2021-01-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0009_auto_20210121_1042"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalphrase",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="historicalphrase",
            name="date",
        ),
        migrations.RemoveField(
            model_name="historicalphrase",
            name="modifier",
        ),
        migrations.RemoveField(
            model_name="phrase",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="phrase",
            name="date",
        ),
        migrations.RemoveField(
            model_name="phrase",
            name="modifier",
        ),
    ]
