# Generated by Django 2.2.17 on 2021-01-26 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0010_auto_20210125_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="analysis",
            field=models.CharField(
                blank=True, help_text="The analysis of the Cree phrase", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When was this phrase last modified?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="modifier",
            field=models.CharField(
                default="AUTO",
                help_text="The person who added or modified the phrase",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="analysis",
            field=models.CharField(
                blank=True, help_text="The analysis of the Cree phrase", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(2021, 1, 26, 16, 24, 42, 590682, tzinfo=utc),
                help_text="When was this phrase last modified?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phrase",
            name="modifier",
            field=models.CharField(
                default="AUTO",
                help_text="The person who added or modified the phrase",
                max_length=64,
            ),
        ),
    ]
