# Generated by Django 2.2.20 on 2021-04-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0010_auto_20210428_1014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="modified_by",
            field=models.CharField(
                default="",
                help_text="The person/people who modified this issue",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="modified_on",
            field=models.DateField(
                help_text="The date this issue was last updated", null=True
            ),
        ),
    ]
