# Generated by Django 2.2.24 on 2021-08-03 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("validation", "0010_issue_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="created_by_reference",
            field=models.ForeignKey(
                help_text="Reference to user who filed the Issue",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
