# Generated by Django 2.2.24 on 2021-08-12 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("validation", "0010_issue_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecording",
            name="is_user_submitted",
            field=models.BooleanField(
                default=False, help_text="This recording was submitted online by a user"
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="is_user_submitted",
            field=models.BooleanField(
                default=False, help_text="This recording was submitted online by a user"
            ),
        ),
        migrations.AddField(
            model_name="speaker",
            name="user",
            field=models.ForeignKey(
                help_text="The User object associated with this Speaker, if any",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalphrase",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("auto-standardized", "Auto-standardized"),
                    ("standardized", "Standardized"),
                    ("linked", "Linked"),
                    ("validated", "Validated"),
                    ("needs review", "Needs review"),
                    ("user-submitted", "User-submitted"),
                ],
                default="new",
                help_text="Status in the validation process",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("auto-standardized", "Auto-standardized"),
                    ("standardized", "Standardized"),
                    ("linked", "Linked"),
                    ("validated", "Validated"),
                    ("needs review", "Needs review"),
                    ("user-submitted", "User-submitted"),
                ],
                default="new",
                help_text="Status in the validation process",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="validation.RecordingSession",
            ),
        ),
    ]
