# Generated by Django 2.2.17 on 2021-01-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0011_auto_20210126_0924"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalphrase",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="historicalphrase",
            name="date",
        ),
        migrations.RemoveField(
            model_name="historicalphrase",
            name="modifier",
        ),
        migrations.RemoveField(
            model_name="phrase",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="phrase",
            name="date",
        ),
        migrations.RemoveField(
            model_name="phrase",
            name="modifier",
        ),
    ]
