# Generated by Django 2.2.24 on 2021-08-03 16:38

from django.db import migrations
from django.db.migrations import RunPython


def infer_user_object(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Issue = apps.get_model("validation", "Issue")
    User = apps.get_model("auth", "User")
    db_alias = schema_editor.connection.alias
    for i in Issue.objects.using(db_alias).all():
        username = i.created_by
        user = User.objects.using(db_alias).filter(username=username).first()
        if not user:
            continue
        i.created_by_reference = user
        i.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0011_add_user_key_to_issue"),
    ]

    operations = [RunPython(infer_user_object, do_nothing)]
