# Generated by Django 2.2.20 on 2021-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0011_auto_20210428_1100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="The comment left by the validator",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="suggested_cree",
            field=models.CharField(
                blank=True,
                help_text="The Cree spelling suggested by the validator",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="suggested_english",
            field=models.CharField(
                blank=True,
                help_text="The English spelling suggested by the validator",
                max_length=1024,
                null=True,
            ),
        ),
    ]
