# Generated by Django 2.2.24 on 2021-08-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0011_user_recording_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="crk_bio_text",
            field=models.CharField(
                blank=True,
                help_text="The Cree transcription of the speaker bio",
                max_length=4096,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="eng_bio_text",
            field=models.CharField(
                blank=True,
                help_text="The English transcription of the speaker bio",
                max_length=4096,
                null=True,
            ),
        ),
    ]
