# Generated by Django 2.2.24 on 2021-08-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0011_auto_20210810_1611"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="validation.RecordingSession",
            ),
        ),
    ]
