# Generated by Django 2.2.24 on 2021-08-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0012_increase_bio_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the dialect", max_length=256
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The three character code for this language",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
