# Generated by Django 2.2.24 on 2021-08-03 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0012_populate_created_by_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="created_by_reference",
            field=models.ForeignKey(
                help_text="Reference to user who filed the Issue",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
