# Generated by Django 2.2.20 on 2021-04-28 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0012_auto_20210428_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="created_on",
            field=models.DateField(
                default=datetime.datetime(2021, 4, 28, 15, 51, 31, 913841),
                help_text="When was this issue filed?",
            ),
        ),
    ]
