# Generated by Django 2.2.24 on 2021-08-30 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0012_increase_bio_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The User object associated with this Speaker, if any",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
