# Generated by Django 2.2.24 on 2021-09-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0013_make_user_nullable_on_speaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="word_id",
            field=models.CharField(
                help_text="Typically, this is the os##### for Tsuut'ina recordings",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="word_id",
            field=models.CharField(
                help_text="Typically, this is the os##### for Tsuut'ina recordings",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalphrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("SRS", "Tsuut'ina Dictionary"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("SRS", "Tsuut'ina Dictionary"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=3,
                null=True,
            ),
        ),
    ]
