# Generated by Django 2.2.24 on 2021-09-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0013_make_user_nullable_on_speaker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the dialect", max_length=256
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The three character code for this language + an additional identifier",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A short description of this language/where it is spoken",
                        max_length=1024,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="dialect",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The dialect this phrase belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="validation.Dialect",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="dialect",
            field=models.ForeignKey(
                help_text="The dialect this phrase belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="validation.Dialect",
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="dialect",
            field=models.ForeignKey(
                help_text="The dialect this phrase belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="validation.Dialect",
            ),
        ),
        migrations.AddField(
            model_name="speaker",
            name="dialects",
            field=models.ManyToManyField(blank=True, to="validation.Dialect"),
        ),
    ]
