# Generated by Django 2.2.24 on 2021-08-17 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0013_dialect"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="dialect",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The dialect this phrase belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="validation.Dialect",
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="dialect",
            field=models.ForeignKey(
                help_text="The dialect this phrase belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="validation.Dialect",
            ),
        ),
    ]
