# Generated by Django 2.2.24 on 2021-09-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0014_dialect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="suggested_cree",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="suggested_english",
        ),
        migrations.AddField(
            model_name="issue",
            name="source_language_suggestion",
            field=models.CharField(
                blank=True,
                help_text="The Source Language spelling suggestion from the validator",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="source_language_suggestion",
            field=models.CharField(
                blank=True,
                help_text="The Target Language spelling suggestion from the validator",
                max_length=1024,
            ),
        ),
    ]
