# Generated by Django 2.2.24 on 2021-08-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0014_add_dialect_to_phrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialect",
            name="description",
            field=models.CharField(
                help_text="A short description of this language/where it is spoken",
                max_length=1024,
                null=True,
            ),
        ),
    ]
