# Generated by Django 2.2.24 on 2021-08-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0014_add_modifier_info"),
    ]

    operations = [
        # TODO: uncomment this when we know for sure none of the
        # issues have been negatively impacted by these changes
        # migrations.RemoveField(
        #     model_name='Issue',
        #     name='created_by',
        # ),
        # migrations.RenameField(
        #     model_name="Issue",
        #     old_name="created_by_reference",
        #     new_name="created_by"
        # )
    ]
