# Generated by Django 2.2.20 on 2021-04-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0014_auto_20210429_1616"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecording",
            name="wrong_speaker",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong speaker"
            ),
        ),
        migrations.AddField(
            model_name="historicalrecording",
            name="wrong_word",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong word"
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="wrong_speaker",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong speaker"
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="wrong_word",
            field=models.BooleanField(
                default=False, help_text="This recording has the wrong word"
            ),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
