# Generated by Django 2.2.24 on 2021-10-29 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0014_speaker_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the language", max_length=256
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="A url-safe identifier for this language",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A short description of this language/where it is spoken",
                        max_length=1024,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="speaker",
            old_name="crk_bio_audio",
            new_name="source_bio_audio",
        ),
        migrations.RenameField(
            model_name="speaker",
            old_name="eng_bio_audio",
            new_name="target_bio_audio",
        ),
        migrations.RenameField(
            model_name="speaker",
            old_name="eng_bio_text",
            new_name="target_bio_text",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="suggested_cree",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="suggested_english",
        ),
        migrations.RemoveField(
            model_name="speaker",
            name="crk_bio_text",
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="osid",
            field=models.CharField(
                help_text="Typically, this is the os##### for Tsuut'ina recordings",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="source_language_suggestion",
            field=models.CharField(
                blank=True,
                help_text="The Target Language spelling suggestion from the validator",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="target_language_suggestion",
            field=models.CharField(
                blank=True,
                help_text="The Source Language spelling suggestion from the validator",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="osid",
            field=models.CharField(
                help_text="Typically, this is the os##### for Tsuut'ina recordings",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="speaker",
            name="source_bio_text",
            field=models.CharField(
                blank=True,
                help_text="The Cree transcription of the speaker bio",
                max_length=4096,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalphrase",
            name="analysis",
            field=models.CharField(
                blank=True, help_text="The analysis of the phrase", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="historicalphrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("OS", "Onespot-Sapir Dictionary"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalphrase",
            name="transcription",
            field=models.CharField(
                help_text="The validated transciption of the target language phrase.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="analysis",
            field=models.CharField(
                blank=True, help_text="The analysis of the phrase", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("OS", "Onespot-Sapir Dictionary"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="transcription",
            field=models.CharField(
                help_text="The validated transciption of the target language phrase.",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="language",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The language this phrase belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="validation.LanguageVariant",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="language",
            field=models.ForeignKey(
                help_text="The language this phrase belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="validation.LanguageVariant",
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="language",
            field=models.ForeignKey(
                help_text="The language this phrase belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="validation.LanguageVariant",
            ),
        ),
        migrations.AddField(
            model_name="speaker",
            name="languages",
            field=models.ManyToManyField(blank=True, to="validation.LanguageVariant"),
        ),
    ]
