# Generated by Django 2.2.24 on 2021-09-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0015_auto_20210916_1609"),
        ("validation", "0014_dialect"),
    ]

    operations = []
