# Generated by Django 2.2.24 on 2021-09-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0015_auto_20210923_1514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="analysis",
            field=models.CharField(
                blank=True, help_text="The analysis of the phrase", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="historicalphrase",
            name="transcription",
            field=models.CharField(
                help_text="The validated transciption of the target language phrase.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="analysis",
            field=models.CharField(
                blank=True, help_text="The analysis of the phrase", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="transcription",
            field=models.CharField(
                help_text="The validated transciption of the target language phrase.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="crk_bio_text",
            field=models.CharField(
                blank=True,
                help_text="The Cree transcription of the speaker bio",
                max_length=4096,
                null=True,
            ),
        ),
    ]
