# Generated by Django 2.2.24 on 2021-11-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0016_language_variants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("OS", "Onespot-Sapir Dictionary"),
                    ("TVPD", "Tsuut'ina Verb Phrase Dictionary"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("OS", "Onespot-Sapir Dictionary"),
                    ("TVPD", "Tsuut'ina Verb Phrase Dictionary"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=4,
                null=True,
            ),
        ),
    ]
