# Generated by Django 2.2.24 on 2021-09-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0017_auto_20210917_1426"),
        ("validation", "0016_auto_20210928_1406"),
    ]

    operations = []
