# Generated by Django 2.2.25 on 2021-12-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0018_add_pfn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("OS", "Onespot-Sapir Dictionary"),
                    ("TVPD", "Tsuut'ina Verb Phrase Dictionary"),
                    ("PFN", "Paul First Nation"),
                    ("AUTO", "Auto-synthesized speech"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("OS", "Onespot-Sapir Dictionary"),
                    ("TVPD", "Tsuut'ina Verb Phrase Dictionary"),
                    ("PFN", "Paul First Nation"),
                    ("AUTO", "Auto-synthesized speech"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=4,
                null=True,
            ),
        ),
    ]
