# Generated by Django 2.2.24 on 2021-09-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0018_merge_20210928_1837"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="target_language_suggestion",
            field=models.CharField(
                blank=True,
                help_text="The Source Language spelling suggestion from the validator",
                max_length=1024,
            ),
        ),
    ]
