# Generated by Django 2.1.2 on 2018-11-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0019_auto_20181024_1601'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recordingsession',
            unique_together={('date', 'time_of_day', 'location', 'subsession')},
        ),
    ]
