# Generated by Django 2.2.24 on 2021-10-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0020_auto_20211019_1336"),
        ("validation", "0014_speaker_image"),
    ]

    operations = []
