# Generated by Django 2.2.26 on 2022-03-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0020_languagevariant_language_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecording",
            name="is_best",
            field=models.BooleanField(
                default=False, help_text="Is this the best recording of the bunch?"
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="is_best",
            field=models.BooleanField(
                default=False, help_text="Is this the best recording of the bunch?"
            ),
        ),
    ]
