# Generated by Django 2.1.2 on 2018-11-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0020_auto_20181101_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingsession',
            name='id',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='recordingsession',
            unique_together=set(),
        ),
    ]
