# Generated by Django 2.2.26 on 2022-04-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0022_add_endonym"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecording",
            name="was_user_submitted",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="This recording was submitted online by a user, but is now approved",
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="was_user_submitted",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="This recording was submitted online by a user, but is now approved",
            ),
        ),
    ]
