# Generated by Django 2.2.26 on 2022-04-18 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("validation", "0023_was_user_submitted"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("metadata", "Metadata"),
                            ("manual classification", "Manual Classification"),
                            ("elicitation sheet", "Elicitation Sheet"),
                        ],
                        help_text="How did we determine this class?",
                        max_length=21,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rapidwords", "RapidWords"),
                            ("wordnet", "WordNet"),
                            ("other", "Other"),
                        ],
                        help_text="Where did this class come from?",
                        max_length=10,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        help_text="The classification for this semantic class",
                        max_length=256,
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        help_text="The phrase this class belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="validation.Phrase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSemanticClass",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("metadata", "Metadata"),
                            ("manual classification", "Manual Classification"),
                            ("elicitation sheet", "Elicitation Sheet"),
                        ],
                        help_text="How did we determine this class?",
                        max_length=21,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rapidwords", "RapidWords"),
                            ("wordnet", "WordNet"),
                            ("other", "Other"),
                        ],
                        help_text="Where did this class come from?",
                        max_length=10,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        help_text="The classification for this semantic class",
                        max_length=256,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The phrase this class belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="validation.Phrase",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical semantic class",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
