# Generated by Django 2.2.26 on 2022-04-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0024_semantic_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsemanticclass",
            name="phrase",
        ),
        migrations.RemoveField(
            model_name="semanticclass",
            name="phrase",
        ),
        migrations.AddField(
            model_name="phrase",
            name="semantic_class",
            field=models.ManyToManyField(blank=True, to="validation.SemanticClass"),
        ),
    ]
