# Generated by Django 2.2.26 on 2022-05-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0025_phrase_has_semantic_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("OS", "Onespot-Sapir Dictionary"),
                    ("TVPD", "Tsuut'ina Verb Phrase Dictionary"),
                    ("PFN", "Paul First Nation"),
                    ("I3", "Îethka Îabi Institude"),
                    ("AUTO", "Auto-synthesized speech"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("OS", "Onespot-Sapir Dictionary"),
                    ("TVPD", "Tsuut'ina Verb Phrase Dictionary"),
                    ("PFN", "Paul First Nation"),
                    ("I3", "Îethka Îabi Institude"),
                    ("AUTO", "Auto-synthesized speech"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=4,
                null=True,
            ),
        ),
    ]
