# Generated by Django 2.2.26 on 2022-05-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0028_auto_20220512_1536"),
    ]

    operations = [
        migrations.AddField(
            model_name="semanticclass",
            name="hypernyms",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="_semanticclass_hypernyms_+",
                to="validation.SemanticClass",
            ),
        ),
        migrations.AddField(
            model_name="semanticclass",
            name="hyponyms",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="_semanticclass_hyponyms_+",
                to="validation.SemanticClass",
            ),
        ),
    ]
