# Generated by Django 2.2.26 on 2022-07-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0029_hypernym_hyponym"),
    ]

    operations = [
        migrations.AddField(
            model_name="semanticclass",
            name="language_variants",
            field=models.ManyToManyField(
                blank=True, default=None, to="validation.LanguageVariant"
            ),
        ),
    ]
