# Generated by Django 2.2.28 on 2024-06-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0030_add_language_variant_to_semantic_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="phrase",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="speaker",
            name="image_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
