# Generated by Django 4.2.15 on 2024-08-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0032_auto_20240819_1535"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semanticclass",
            name="hypernyms",
            field=models.ManyToManyField(
                blank=True, default=None, to="validation.semanticclass"
            ),
        ),
        migrations.AlterField(
            model_name="semanticclass",
            name="hyponyms",
            field=models.ManyToManyField(
                blank=True, default=None, to="validation.semanticclass"
            ),
        ),
    ]
