# Generated by Django 4.2.15 on 2024-08-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0033_alter_semanticclass_hypernyms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecording",
            name="updated_compressed_audio",
            field=models.BooleanField(
                default=False,
                help_text="Whether this recording was reprocessed. If true, likely the original version had the incorrect track for the session",
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="updated_compressed_audio",
            field=models.BooleanField(
                default=False,
                help_text="Whether this recording was reprocessed. If true, likely the original version had the incorrect track for the session",
            ),
        ),
    ]
