# Generated by Django 4.2.15 on 2024-08-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0034_historicalrecording_updated_compressed_audio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrecording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("good", "Good"),
                    ("ok", "OK"),
                    ("bad", "Bad"),
                    ("unknown", "Unknown"),
                ],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("good", "Good"),
                    ("ok", "OK"),
                    ("bad", "Bad"),
                    ("unknown", "Unknown"),
                ],
                help_text="Is the recording clean? Is it suitable to use publicly?",
                max_length=64,
            ),
        ),
    ]
