# Generated by Django 4.2.15 on 2024-08-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0035_alter_historicalrecording_quality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="lexical_category",
            field=models.CharField(
                blank=True, help_text="The Lexical Category of the word", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="stem",
            field=models.CharField(
                blank=True, help_text="The stem of the word", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="lexical_category",
            field=models.CharField(
                blank=True, help_text="The Lexical Category of the word", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="stem",
            field=models.CharField(
                blank=True, help_text="The stem of the word", max_length=256
            ),
        ),
    ]
