# Generated by Django 4.2.15 on 2024-09-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0036_historicalphrase_lexical_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="Short code assigned to collection",
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The collection's name", max_length=2048
                    ),
                ),
                ("comment", models.TextField()),
            ],
        ),
    ]
