# Generated by Django 4.2.15 on 2024-09-09 18:33

from django.db import migrations, models
import django.db.models.deletion
import validation.models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0038_auto_20240909_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecording",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=validation.models.get_default_collection,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="validation.collection",
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="collection",
            field=models.ForeignKey(
                default=validation.models.get_default_collection,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="validation.collection",
            ),
        ),
    ]
