# Generated by Django 4.2.15 on 2024-09-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0039_historicalrecording_collection_recording_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="speaker_suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="validation.speaker",
            ),
        ),
    ]
