# Generated by Django 4.2.15 on 2024-09-26 19:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("validation", "0041_auto_20240912_1503"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalSemanticClass",
            new_name="HistoricalSemanticClassAnnotation",
        ),
        migrations.RenameModel(
            old_name="SemanticClass",
            new_name="SemanticClassAnnotation",
        ),
        migrations.AlterModelOptions(
            name="historicalsemanticclassannotation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical semantic class annotation",
                "verbose_name_plural": "historical semantic class annotations",
            },
        ),
    ]
