# Generated by Django 4.2.15 on 2024-09-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "validation",
            "0042_rename_historicalsemanticclass_historicalsemanticclassannotation_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.CharField(
                        choices=[
                            ("rapidwords", "RapidWords"),
                            ("wordnet", "WordNet"),
                            ("other", "Other"),
                        ],
                        help_text="What collection does this class belong to?",
                        max_length=10,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        help_text="The classification for this semantic class",
                        max_length=256,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="semanticclass",
            constraint=models.UniqueConstraint(
                fields=("collection", "classification"),
                name="unique_semantic_classification_per_collection",
            ),
        ),
    ]
