# Generated by Django 4.2.15 on 2024-09-26 21:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("validation", "0044_auto_20240926_1410"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalSemanticClassAnnotation",
            new_name="HistoricalSemanticClassOldAnnotation",
        ),
        migrations.RenameModel(
            old_name="SemanticClassAnnotation",
            new_name="SemanticClassOldAnnotation",
        ),
        migrations.AlterModelOptions(
            name="historicalsemanticclassoldannotation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical semantic class old annotation",
                "verbose_name_plural": "historical semantic class old annotations",
            },
        ),
    ]
