# Generated by Django 4.2.15 on 2024-09-26 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "validation",
            "0045_rename_historicalsemanticclassannotation_historicalsemanticclassoldannotation_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticClassAnnotation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("metadata", "Metadata"),
                            ("manual classification", "Manual Classification"),
                            ("elicitation sheet", "Elicitation Sheet"),
                        ],
                        help_text="How did we determine this class?",
                        max_length=21,
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="validation.phrase",
                    ),
                ),
                (
                    "semantic_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="validation.semanticclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSemanticClassAnnotation",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("metadata", "Metadata"),
                            ("manual classification", "Manual Classification"),
                            ("elicitation sheet", "Elicitation Sheet"),
                        ],
                        help_text="How did we determine this class?",
                        max_length=21,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="validation.phrase",
                    ),
                ),
                (
                    "semantic_class",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="validation.semanticclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical semantic class annotation",
                "verbose_name_plural": "historical semantic class annotations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="phrase",
            name="semantic_classes",
            field=models.ManyToManyField(
                blank=True,
                through="validation.SemanticClassAnnotation",
                to="validation.semanticclass",
            ),
        ),
    ]
