# Generated by Django 4.2.15 on 2024-09-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0047_auto_20240926_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="semanticclass",
            name="hypernyms",
            field=models.ManyToManyField(
                blank=True, default=None, to="validation.semanticclass"
            ),
        ),
        migrations.AddField(
            model_name="semanticclass",
            name="hyponyms",
            field=models.ManyToManyField(
                blank=True, default=None, to="validation.semanticclass"
            ),
        ),
    ]
