# Generated by Django 4.2.15 on 2024-09-27 16:37

from django.db import migrations


def populate_rapidwords_hyper_and_hyponyms(apps, schema_editor):
    SemanticClass = apps.get_model("validation", "SemanticClass")
    populate_hypernyms(SemanticClass)


def populate_hypernyms(SemanticClass):
    for sc in SemanticClass.objects.filter(collection="rapidwords"):
        # Create collection of all hypernym codes to find
        hypernym_candidates = sc.classification.split()[0].strip().split(".")
        hypernyms = []
        hypernym = ""
        for subdomain in hypernym_candidates[0:-1]:
            hypernym += subdomain
            hypernyms.append(hypernym)
            hypernym += "."
        # Nowadd them to the field
        for hypernym in hypernyms:
            sc.hypernyms.add(
                SemanticClass.objects.filter(collection="rapidwords").get(
                    classification__startswith=hypernym + " "
                )
            )


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0048_semanticclass_hypernyms_semanticclass_hyponyms"),
    ]

    operations = [migrations.RunPython(populate_rapidwords_hyper_and_hyponyms)]
