# Generated by Django 4.2.15 on 2024-09-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0049_auto_20240927_1037"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semanticclass",
            name="hyponyms",
        ),
    ]
