# Generated by Django 4.2.15 on 2024-09-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0050_remove_semanticclass_hyponyms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semanticclass",
            name="hypernyms",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="hyponyms",
                to="validation.semanticclass",
            ),
        ),
    ]
