# Generated by Django 4.2.15 on 2024-10-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0053_alter_phrase_semantic_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsemanticclassannotation",
            name="dictionary_source",
            field=models.CharField(
                blank=True,
                choices=[("CW", "Cree: Words"), ("MD", "Maskwacis Dictionary")],
                help_text="If annotation came from dictionary, which one?",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="semanticclassannotation",
            name="dictionary_source",
            field=models.CharField(
                blank=True,
                choices=[("CW", "Cree: Words"), ("MD", "Maskwacis Dictionary")],
                help_text="If annotation came from dictionary, which one?",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsemanticclassannotation",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("metadata", "Metadata"),
                    ("manual classification", "Manual Classification"),
                    ("elicitation sheet", "Elicitation Sheet"),
                    ("dictionary", "Dictionary"),
                ],
                help_text="How did we determine this class?",
                max_length=21,
            ),
        ),
        migrations.AlterField(
            model_name="semanticclassannotation",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("metadata", "Metadata"),
                    ("manual classification", "Manual Classification"),
                    ("elicitation sheet", "Elicitation Sheet"),
                    ("dictionary", "Dictionary"),
                ],
                help_text="How did we determine this class?",
                max_length=21,
            ),
        ),
    ]
