# Generated by Django 4.2.18 on 2025-01-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "validation",
            "0054_historicalsemanticclassannotation_dictionary_source_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("OS", "Onespot-Sapir Dictionary"),
                    ("TVPD", "Tsuut'ina Verb Phrase Dictionary"),
                    ("TPRP", "Tsuut'ina Paradigm Recording Project"),
                    ("PFN", "Paul First Nation"),
                    ("I3", "Îethka Îabi Institude"),
                    ("AUTO", "Auto-synthesized speech"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MD", "Maskwacîs Dictionary"),
                    ("OS", "Onespot-Sapir Dictionary"),
                    ("TVPD", "Tsuut'ina Verb Phrase Dictionary"),
                    ("TPRP", "Tsuut'ina Paradigm Recording Project"),
                    ("PFN", "Paul First Nation"),
                    ("I3", "Îethka Îabi Institude"),
                    ("AUTO", "Auto-synthesized speech"),
                    ("new", "New word"),
                ],
                default="new",
                help_text="How did we get this phrase?",
                max_length=4,
                null=True,
            ),
        ),
    ]
