# Generated by Django 4.2.23 on 2025-09-12 17:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0055_alter_historicalphrase_origin_alter_phrase_origin"),
    ]

    operations = []

    def add_history_relation(apps, schema_editor):
        HistoricalModel = apps.get_model("validation", "HistoricalPhrase")
        # "id" may differ depending on your base model's primary key field
        HistoricalModel.objects.update(history_relation=models.F("id"))

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="history_relation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=models.deletion.DO_NOTHING,
                related_name="historical_records",
                to="validation.Phrase",
            ),
        ),
        migrations.RunPython(add_history_relation, migrations.RunPython.noop),
    ]
