# Generated by Django 4.2.23 on 2025-09-12 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0056_auto_20250912_1140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="historical_records",
                to="validation.phrase",
            ),
        ),
    ]
