# Generated by Django 4.2.24 on 2025-09-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0057_alter_historicalphrase_history_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphrase",
            name="osid",
            field=models.CharField(
                blank=True,
                help_text="Typically, this is the os##### for Tsuut'ina recordings",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="osid",
            field=models.CharField(
                blank=True,
                help_text="Typically, this is the os##### for Tsuut'ina recordings",
                max_length=16,
                null=True,
            ),
        ),
    ]
