# Generated by Django 4.2.24 on 2025-09-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0058_alter_historicalphrase_osid_alter_phrase_osid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                help_text="Gender of the voice.",
                max_length=1,
                null=True,
            ),
        ),
    ]
