# Generated by Django 4.2.24 on 2025-09-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0059_alter_speaker_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="is_excluded",
            field=models.BooleanField(
                default=False, help_text="Exclude from results but keep in the database"
            ),
        ),
        migrations.AddField(
            model_name="historicalrecording",
            name="is_excluded",
            field=models.BooleanField(
                default=False, help_text="Exclude from results but keep in the database"
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="is_excluded",
            field=models.BooleanField(
                default=False, help_text="Exclude from results but keep in the database"
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="is_excluded",
            field=models.BooleanField(
                default=False, help_text="Exclude from results but keep in the database"
            ),
        ),
        migrations.AddField(
            model_name="recordingsession",
            name="is_excluded",
            field=models.BooleanField(
                default=False, help_text="Exclude from results but keep in the database"
            ),
        ),
    ]
